version: 2

sources:
  - name: staging
    database: staging
    schema: staging
    tables:
      - name: stg_orders
      - name: stg_order_items
      - name: stg_payments
      - name: stg_customers
      - name: stg_products
      - name: stg_order_reviews