version: 2

sources:
  - name: raw
    database: raw
    schema: raw
    tables:
      - name: orders
      - name: order_items
      - name: payments
      - name: customers
      - name: products
      - name: order_reviews
      - name: orders_stream
      - name: order_items_stream
      - name: payments_stream